BEGIN;

CREATE TABLE IF NOT EXISTS public.risk_layer_config (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    risk_key varchar NOT NULL,
    label varchar NOT NULL,
    table_name varchar NOT NULL,
    geometry_column varchar NOT NULL DEFAULT 'geom',
    class_column varchar NOT NULL DEFAULT 'kelas',
    display_order integer NOT NULL DEFAULT 0,
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT risk_layer_config_risk_key_key UNIQUE (risk_key),
    CONSTRAINT risk_layer_config_table_name_key UNIQUE (table_name)
);

INSERT INTO public.risk_layer_config
    (id, risk_key, label, table_name, geometry_column, class_column, display_order, enabled)
VALUES
    (1, 'karhutla', 'Kebakaran Hutan dan Lahan', 'risiko_karhutla', 'geom_valid', 'kelas', 1, true),
    (2, 'longsor', 'Longsor', 'risiko_longsor', 'geom_valid', 'kelas', 2, true),
    (3, 'abrasi', 'Abrasi', 'risiko_abrasi', 'geom_valid', 'kelas', 3, true),
    (4, 'kekeringan', 'Kekeringan', 'risiko_kekeringan', 'geom_valid', 'kelas', 4, true),
    (5, 'banjir_bandang', 'Banjir Bandang', 'risiko_banjir_bandang', 'geom_valid', 'kelas', 5, true),
    (6, 'banjir', 'Banjir', 'risiko_banjir', 'geom_valid', 'kelas', 6, true)
ON CONFLICT (id) DO UPDATE SET
    risk_key = EXCLUDED.risk_key,
    label = EXCLUDED.label,
    table_name = EXCLUDED.table_name,
    geometry_column = EXCLUDED.geometry_column,
    class_column = EXCLUDED.class_column,
    display_order = EXCLUDED.display_order,
    enabled = EXCLUDED.enabled,
    updated_at = CURRENT_TIMESTAMP;

COMMIT;
