BEGIN;

CREATE TABLE IF NOT EXISTS public.risk_class_score (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_name varchar(100) NOT NULL,
    score integer NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT risk_class_score_class_name_key UNIQUE (class_name)
);

INSERT INTO public.risk_class_score
    (id, class_name, score, enabled)
VALUES
    (1, 'Rendah', 1, true),
    (2, 'Sedang', 2, true),
    (3, 'Tinggi', 3, true)
ON CONFLICT (id) DO UPDATE SET
    class_name = EXCLUDED.class_name,
    score = EXCLUDED.score,
    enabled = EXCLUDED.enabled,
    updated_at = CURRENT_TIMESTAMP;


CREATE TABLE IF NOT EXISTS public.risk_status_rule (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    min_score integer NOT NULL,
    max_score integer NOT NULL,
    status varchar(50) NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT risk_status_rule_score_check CHECK (min_score <= max_score)
);

INSERT INTO public.risk_status_rule
    (id, min_score, max_score, status, enabled)
VALUES
    (1, 5, 7, 'Aman', true),
    (2, 8, 10, 'Siaga', true),
    (3, 11, 13, 'Waspada', true),
    (4, 14, 15, 'Bahaya', true)
ON CONFLICT (id) DO UPDATE SET
    min_score = EXCLUDED.min_score,
    max_score = EXCLUDED.max_score,
    status = EXCLUDED.status,
    enabled = EXCLUDED.enabled,
    updated_at = CURRENT_TIMESTAMP;

COMMIT;
